modLoader = "javafml"
loaderVersion = "[31,)"
license = "LGPLv3"
issueTrackerURL = "${issue}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL = "${homepage}"
authors = "${authors}"
description = '''
${description}
'''
logoFile = "icon.png"

[[dependencies."${id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_dependency}"
ordering = "NONE"
side="BOTH"
