name: Dev Builds

on:
  push:
    paths:
      - "*.gradle"
      - "gradle.properties"
      - "src/**"
      - "versions/**"
      - ".github/**"
      - "buildSrc/**"
      - "settings.json"
  pull_request:


jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
