name: _step.matrix_prepare

on:
  workflow_call:
    outputs:
      matrix:
        description: The generated run matrix
        value: ${{ jobs.matrix_prep.outputs.matrix }}


jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: setmatrix
        run: python3 .github/workflows/scripts/matrix.py

    outputs:
      matrix: ${{ steps.setmatrix.outputs.matrix }}
